package sharoom.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import model.Config;

/**
 * Interface de configuration de 
 * l'adresse d'écoute
 * Date : Mai 2015
 * @author Rija ZAFIAMY
 */
public class ConfigurationDialog extends javax.swing.JDialog {

    /**
     * Creates new form ConfigurationDialog
     * @param parent
     * @param modal
     * @param conf
     */
    
    public ConfigurationDialog(java.awt.Frame parent, boolean modal,Config conf) {
        super(parent, modal);
        initComponents();
        
        this.configuration = conf;
        
        this.setTitle("Configuration");
        
        this.jTextFieldHostInfo.setText(this.configuration.getConfigVariable("IP")+":"+this.configuration.getConfigVariable("PORT"));
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSave = new javax.swing.JButton();
        jTextFieldHostInfo = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(103, 103, 103));

        jButtonSave.setBackground(new java.awt.Color(126, 10, 10));
        jButtonSave.setForeground(new java.awt.Color(254, 247, 247));
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jTextFieldHostInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHostInfoActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel.setText("Host_ip:port (ex: 192.168.0.1:7885)");

        jLabelMessage.setForeground(new java.awt.Color(239, 41, 41));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldHostInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                            .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldHostInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        String uri[] = this.jTextFieldHostInfo.getText().split(":");
        
       
        if((!this.jTextFieldHostInfo.getText().isEmpty())&&(!uri[0].isEmpty())&&(!uri[1].isEmpty()))
        {
           
            this.configuration.setConfigVariable("IP",uri[0]);
            this.configuration.setConfigVariable("PORT",uri[1]);
            
            this.jLabelMessage.setText("");
            
            this.dispose();
        }
        else
        {
            this.jLabelMessage.setText("Please fill empty field !");
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextFieldHostInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHostInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHostInfoActionPerformed

    private Config configuration;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JTextField jTextFieldHostInfo;
    // End of variables declaration//GEN-END:variables
}
