package sharoom.view;

/**
 * Un FolderPanel représente un dossier
 * sur l'interface graphique
 * Date : Mai 2015
 * @author Rija ZAFIAMY
 */
public class FolderPanel extends javax.swing.JPanel {

    private int nb_element;
    
    public FolderPanel(String _foldername) 
    {
        initComponents();
        this.jScrollPane1.getVerticalScrollBar().setUnitIncrement(15);
        this.jLabelFolderName.setText(_foldername);
    }

    public void addFilePanel(FilePanel file)
    {
        this.jPanelFolderList.add(file);
        this.jPanelFolderList.updateUI();
        this.nb_element = this.nb_element + 1;
    }
    
    public int getNum()
    {
        return this.nb_element;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFolderName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelFolderList = new javax.swing.JPanel();

        setBackground(new java.awt.Color(46, 46, 46));
        setMinimumSize(new java.awt.Dimension(50, 200));
        setPreferredSize(new java.awt.Dimension(400, 30));

        jLabelFolderName.setBackground(new java.awt.Color(254, 247, 247));
        jLabelFolderName.setForeground(new java.awt.Color(254, 254, 254));
        jLabelFolderName.setText("Dossier");

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(50, 200));

        jPanelFolderList.setAutoscrolls(true);
        jPanelFolderList.setMinimumSize(new java.awt.Dimension(50, 200));
        jPanelFolderList.setLayout(new javax.swing.BoxLayout(jPanelFolderList, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanelFolderList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFolderName, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelFolderName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFolderName;
    private javax.swing.JPanel jPanelFolderList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
